import React from 'react';
import { useLocation, useNavigate } from 'react-router-dom';
import ReactMarkdown from 'react-markdown';
import remarkGfm from 'remark-gfm';
import { auth } from '../firebase-config';

const ReportViewer = () => {
  const location = useLocation();
  const navigate = useNavigate();
  const { draft, topic, standard } = location.state || {};

  if (!draft) {
    return (
      <div className="page-container">
        <h2>No report to view</h2>
        <button onClick={() => navigate('/report')}>Go back</button>
      </div>
    );
  }

  const handleExport = async (format) => {
    try {
      const user = auth.currentUser;
      const token = await user.getIdToken();

      const apiUrl = import.meta.env.VITE_API_URL || 'https://csrd-api-71795126030.europe-west1.run.app';
      const response = await fetch(`${apiUrl}/export/${format}`, {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
          'Authorization': `Bearer ${token}`
        },
        body: JSON.stringify({
          content: draft,
          title: `${standard.toUpperCase()} - ${topic}`
        }),
      });

      if (!response.ok) throw new Error('Export failed');

      const blob = await response.blob();
      const url = window.URL.createObjectURL(blob);
      const a = document.createElement('a');
      a.href = url;
      a.download = `${standard.toUpperCase()}_${topic}.${format === 'pdf' ? 'pdf' : 'docx'}`;
      document.body.appendChild(a);
      a.click();
      window.URL.revokeObjectURL(url);
      document.body.removeChild(a);
    } catch (error) {
      console.error('Export error:', error);
      alert('Failed to export document');
    }
  };

  return (
    <div className="page-container" style={{ maxWidth: '1000px', margin: '0 auto' }}>
      <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: '2rem' }}>
        <h1>Report Preview</h1>
        <div style={{ display: 'flex', gap: '1rem' }}>
          <button
            className="secondary-button"
            onClick={() => navigate('/report')}
          >
            Back to Edit
          </button>
          <button
            className="primary-button"
            onClick={() => handleExport('docx')}
          >
            Download Word
          </button>
          <button
            className="primary-button"
            onClick={() => handleExport('pdf')}
          >
            Download PDF
          </button>
        </div>
      </div>

      <div className="report-preview" style={{
        backgroundColor: 'white',
        color: 'black',
        padding: '4rem',
        borderRadius: '8px',
        boxShadow: '0 4px 6px rgba(0,0,0,0.1)',
        minHeight: '800px'
      }}>
        <div style={{ textAlign: 'center', marginBottom: '3rem', borderBottom: '2px solid #333', paddingBottom: '1rem' }}>
          <h1 style={{ color: '#333' }}>CSRD Report: {standard.toUpperCase()}</h1>
          <h2 style={{ color: '#666' }}>{topic}</h2>
          <p style={{ color: '#999' }}>Generated by Ecoply AI</p>
        </div>

        <div className="markdown-content" style={{ lineHeight: '1.6' }}>
          <ReactMarkdown remarkPlugins={[remarkGfm]}>
            {draft}
          </ReactMarkdown>
        </div>
      </div>
    </div>
  );
};

export default ReportViewer;
